---
# tasks file for hadoop_master
- name: Add epel repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ epel_url }}"

- name: Download Java9
  get_url:
    url: https://repo.huaweicloud.com/java/jdk/8u171-b11/jdk-8u171-linux-x64.rpm
    dest: /root/jdk-8u171-linux-x64.rpm

- name: Download Hadoopv1.2
  get_url:
    url: https://archive.apache.org/dist/hadoop/core/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm
    dest: /root/hadoop-1.2.1-1.x86_64.rpm

- name: Install java8
  command: rpm -ivh jdk-8u171-linux-x64.rpm

- name: Installing Hadoop
  command: rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force

   
- name: Creating namenodedir
  file:
    path: "{{ nn_dir }}"        
    state: directory

- name: Copy hdfs conf file of hadoop
  template:
    src: "nn_hdfs-site.xml"
    dest: "/etc/hadoop/hdfs-site.xml" 
- name: Copy core conf file of hadoop
  template:
    src: "nn_core-site.xml"
    dest: "/etc/hadoop/core-site.xml"

- name: Formating namenode dir
  command: echo Y | hadoop namenode -format

- name: starting services
  command: hadoop-daemon.sh start namenode  


    
